"""
Phase 1 PDF → Word markup helpers: best-practice tagging + AI suggestions.

Combines deterministic cover-field replacement with optional AI template tagger.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from ai.models import AiAudit, TagSuggestion
from ai.template_tagger import suggest_template_tags, suggestions_to_markdown
from phase1_pdf_text import Phase1PdfMeta, build_mvp_tag_replacements
from scripts.tag_production_template import tag_docx_xml

DEFAULT_AUTO_CONFIDENCE = 0.85


@dataclass
class MarkupResult:
    """Outcome of enhancing a converted Phase 1 template."""

    docx_bytes: bytes
    mvp_replacements: int
    ai_suggestions: list[TagSuggestion] = field(default_factory=list)
    ai_applied: int = 0
    audit: AiAudit | None = None
    skipped_ai: list[str] = field(default_factory=list)


def apply_tag_suggestions(
    docx_bytes: bytes,
    suggestions: list[TagSuggestion],
    *,
    min_confidence: float = DEFAULT_AUTO_CONFIDENCE,
    skip_already_tagged: bool = True,
) -> tuple[bytes, int, list[str]]:
    """
    Apply high-confidence tag suggestions via XML string replace.
    Returns (docx_bytes, applied_count, skipped_original_texts).
    """
    replacements: dict[str, str] = {}
    skipped: list[str] = []
    for s in suggestions:
        if s.confidence < min_confidence:
            skipped.append(s.original_text)
            continue
        if skip_already_tagged and s.confidence >= 1.0:
            continue
        old = s.original_text.strip()
        new = s.jinja_tag.strip()
        if not old or old == new or old in replacements:
            continue
        replacements[old] = new
    if not replacements:
        return docx_bytes, 0, skipped
    ordered = dict(sorted(replacements.items(), key=lambda x: -len(x[0])))
    return tag_docx_xml(docx_bytes, ordered), len(ordered), skipped


def enhance_phase1_markup(
    docx_bytes: bytes,
    meta: Phase1PdfMeta,
    *,
    use_ai: bool = True,
    apply_ai_tags: bool = True,
    use_llm: bool = True,
    min_ai_confidence: float = DEFAULT_AUTO_CONFIDENCE,
) -> MarkupResult:
    """
    Apply MVP cover replacements, then optional AI tagger (phase1_alberta allowlist).
    """
    mvp = build_mvp_tag_replacements(meta)
    tagged = tag_docx_xml(docx_bytes, mvp) if mvp else docx_bytes
    mvp_count = len(mvp)

    suggestions: list[TagSuggestion] = []
    audit: AiAudit | None = None
    ai_applied = 0
    skipped: list[str] = []

    if use_ai:
        suggestions, audit = suggest_template_tags(
            tagged, use_llm=use_llm, report_type="phase1_alberta"
        )
        if apply_ai_tags and suggestions:
            tagged, ai_applied, skipped = apply_tag_suggestions(
                tagged,
                suggestions,
                min_confidence=min_ai_confidence,
            )

    return MarkupResult(
        docx_bytes=tagged,
        mvp_replacements=mvp_count,
        ai_suggestions=suggestions,
        ai_applied=ai_applied,
        audit=audit,
        skipped_ai=skipped,
    )


def write_tagging_guide(
    path: Path,
    suggestions: list[TagSuggestion],
    *,
    meta: Phase1PdfMeta | None = None,
    mvp_count: int = 0,
    ai_applied: int = 0,
) -> None:
    """Write markdown tagging guide (AI table + Phase 1 checklist)."""
    lines = [
        "# Phase 1 template tagging guide",
        "",
        "Generated by ESA Report Generator. **Review in Word** before client use.",
        "",
        "## Best practices",
        "",
        "- Type each `{{ tag }}` in a **single** Word formatting run (no bold inside a tag).",
        "- Cover fields first; expand to AER Schedule Two sections when ready.",
        "- Match Excel `ProjectData` row 2 keys to template tags (see `schemas/report_profiles.json`).",
        "- Run pre-flight in the app before generating; fix split-tag warnings.",
        "",
    ]
    if meta:
        lines.extend(
            [
                "## Parsed from PDF",
                "",
                f"- **Project:** {meta.project_number}",
                f"- **Client:** {meta.client_name}",
                f"- **Site / well:** {meta.site_name}",
                f"- **UWI / LSD:** {meta.uwi}",
                f"- **Report date:** {meta.report_month_year}",
                "",
            ]
        )
    lines.append(f"- **MVP auto-tags applied:** {mvp_count}")
    lines.append(f"- **AI auto-tags applied:** {ai_applied}")
    lines.append("")
    if suggestions:
        lines.append(suggestions_to_markdown(suggestions))
    else:
        lines.append("_No additional AI suggestions (upload template to AI tab for a rescan)._")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def best_practices_checklist(markup_path: Path) -> list[str]:
    """Post-markup CLI checklist lines."""
    return [
        f"Open `{markup_path.name}` in Word — verify cover tags on one formatting run.",
        "Run: python scripts\\inventory_template.py \"" + str(markup_path) + "\"",
        "Pair with samples\\phase1_<site>_data.xlsx and test:",
        "  python scripts\\test_with_your_documents.py --excel ... --template ...",
        "Optional: AI tab - Narrative drafts for executive_summary refinement.",
    ]


def excel_row_from_meta(meta: Phase1PdfMeta, *, draft_narratives: bool = False) -> dict[str, str]:
    """Build ProjectData-style overrides from PDF metadata."""
    from engine import ECOVENTURE_CONSULTANT

    row: dict[str, str] = {
        "client_name": meta.client_name,
        "consultant_name": ECOVENTURE_CONSULTANT,
        "company": ECOVENTURE_CONSULTANT,
        "well_name": meta.well_name,
        "site_name": meta.site_name,
        "uwi": meta.uwi,
        "project_number": meta.project_number,
        "report_title": meta.report_title,
        "report_month_year": meta.report_month_year,
    }
    if draft_narratives:
        from phase1_narrative import build_phase1_executive_summary

        row["executive_summary"] = build_phase1_executive_summary(row)
        try:
            from ai.narrative import draft_narratives

            drafts, _audit = draft_narratives(
                row,
                sections=["conclusions_recommendations"],
                use_llm=False,
            )
            for d in drafts:
                if d.section == "conclusions_recommendations" and d.text:
                    row["conclusions_recommendations"] = d.text[:8000]
        except Exception:
            pass
    return row
